### PR TITLE
Remove function from private xarray module

### LINKED ISSUE #338: Upstream CI failure - xarray update
https://github.com/pangeo-data/xESMF/actions/runs/7880164199

Test failures triggered by some changes in xarray regarding the `xr.core.pycompat` submodule.

On the other hand, the last run was made with ESMF 8.6, and it seems like no errors were related to this long awaited upgrade!

### PR DESCRIPTION
**Pull request by aulemahal**
Fixes #338 

We were using a method from `xr.core.pycompat` that was removed. That module is private, so this was a mistake on our end.

Also, the method was only used to check if a dataArray was dask-backed and load it if it was. However, calling `load()` on any array has the exact same effect anyway.

Seeing how this impacted downstream packages, this might warrant a minor or patch release!

### CODE REVIEW

**Comment by TomNicholas** [comment]
Another option is to just copy the original code for `is_dask_collection` from xarray into xESMF if you really need it.

**Comment by aulemahal** [comment]
Hum, turns out `cf-xarray` as the same issue! I'll open a PR and issue.

**Comment by aulemahal** [comment]
See https://github.com/xarray-contrib/cf-xarray/pull/502

**Review by huard — APPROVED** [review]

**Comment by aulemahal** [comment]
To trigger tests again.

**Pull request merged**
